"""Models for the Planning Engine, including Pydantic models for BrainState representation and SQLAlchemy models for DB persistence."""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field

from sqlalchemy import Column, String, Float, Integer, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID, JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base


# =====================================================================
# PYDANTIC SCHEMAS
# =====================================================================

class Step(BaseModel):
    """Represents a discrete step inside an execution plan DAG."""
    step_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    title: str
    description: str
    order: int
    status: str = "pending"  # pending, running, completed, failed
    
    # Requirement Flags
    tool_required: Optional[str] = None
    memory_required: bool = False
    knowledge_required: bool = False
    rag_required: bool = False
    automation_required: bool = False
    approval_required: bool = False
    
    # Estimations
    estimated_duration: float = 0.0  # seconds
    estimated_tokens: int = 0
    retry_count: int = 0
    
    # Graph Links
    dependencies: List[str] = Field(default_factory=list)
    parallel_group: Optional[str] = None
    rollback_step: Optional[str] = None


class Plan(BaseModel):
    """Represents a complete executable plan DAG generated by the planner."""
    plan_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    goal: str
    summary: str
    confidence: float = 1.0
    created_time: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    estimated_cost: float = 0.0  # dollar estimate
    estimated_duration: float = 0.0  # seconds
    execution_strategy: str = "sequential"  # sequential, parallel, dynamic
    status: str = "pending"  # pending, running, completed, failed, rolled_back
    steps: List[Step] = Field(default_factory=list)


# =====================================================================
# SQLALCHEMY PERSISTENT MODELS
# =====================================================================

class PlanRecord(Base):
    """Persistent database table representation of generated Plans."""
    
    __tablename__ = "brain_plans"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id = Column(UUID(as_uuid=True), nullable=False, index=True)
    goal = Column(Text, nullable=False)
    summary = Column(Text, nullable=False)
    confidence = Column(Float, default=1.0)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    estimated_cost = Column(Float, default=0.0)
    estimated_duration = Column(Float, default=0.0)
    execution_strategy = Column(String(50), default="sequential")
    status = Column(String(50), default="pending")
    metadata_ = Column("metadata", JSONB, nullable=True)

    steps = relationship("PlanStepRecord", back_populates="plan", cascade="all, delete-orphan")


class PlanStepRecord(Base):
    """Persistent database table representation of individual Plan Steps."""
    
    __tablename__ = "brain_plan_steps"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    plan_id = Column(UUID(as_uuid=True), ForeignKey("brain_plans.id", ondelete="CASCADE"), nullable=False, index=True)
    title = Column(String(255), nullable=False)
    description = Column(Text, nullable=False)
    step_order = Column(Integer, nullable=False)
    status = Column(String(50), default="pending")
    
    # Requirement Flags
    tool_required = Column(String(255), nullable=True)
    memory_required = Column(Boolean, default=False)
    knowledge_required = Column(Boolean, default=False)
    rag_required = Column(Boolean, default=False)
    automation_required = Column(Boolean, default=False)
    approval_required = Column(Boolean, default=False)
    
    # Estimations
    estimated_duration = Column(Float, default=0.0)
    estimated_tokens = Column(Integer, default=0)
    retry_count = Column(Integer, default=0)

    # Graph Links
    dependencies = Column(JSONB, nullable=True)  # List[str] step titles
    parallel_group = Column(String(255), nullable=True)
    rollback_step = Column(Text, nullable=True)

    plan = relationship("PlanRecord", back_populates="steps")
