"""add_attachment_processing_columns

Revision ID: 0dba6c709705
Revises: abfaf894e17c
Create Date: 2026-07-11 15:42:41.468552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dba6c709705'
down_revision: Union[str, Sequence[str], None] = 'abfaf894e17c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('attachments', sa.Column('attachment_summary', sa.Text(), nullable=True))
    op.add_column('attachments', sa.Column('processing_status', sa.String(length=50), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attachments', 'processing_status')
    op.drop_column('attachments', 'attachment_summary')
    op.drop_column('attachments', 'extracted_text')
    # ### end Alembic commands ###
