"""create_connector_and_communication_tables

Revision ID: 7aaffaf15651
Revises: 8047cc3f9469
Create Date: 2026-06-29 15:25:32.917539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7aaffaf15651'
down_revision: Union[str, Sequence[str], None] = '8047cc3f9469'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', postgresql.ENUM('GMAIL', 'WHATSAPP', 'SLACK', 'DISCORD', 'TELEGRAM', 'GOOGLE_CALENDAR', 'GOOGLE_DRIVE', 'MICROSOFT_TEAMS', 'ZOOM', name='platform', create_type=False), nullable=False),
    sa.Column('platform_conversation_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_platform_conversation_id'), 'conversations', ['platform_conversation_id'], unique=False)
    op.create_table('connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platform', postgresql.ENUM('GMAIL', 'WHATSAPP', 'SLACK', 'DISCORD', 'TELEGRAM', 'GOOGLE_CALENDAR', 'GOOGLE_DRIVE', 'MICROSOFT_TEAMS', 'ZOOM', name='platform', create_type=False), nullable=False),
    sa.Column('state', sa.Enum('DISCONNECTED', 'AUTHORIZING', 'CONNECTED', 'SYNCING', 'ERROR', 'EXPIRED', 'RECONNECT_REQUIRED', name='connectorstate'), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=True),
    sa.Column('platform', postgresql.ENUM('GMAIL', 'WHATSAPP', 'SLACK', 'DISCORD', 'TELEGRAM', 'GOOGLE_CALENDAR', 'GOOGLE_DRIVE', 'MICROSOFT_TEAMS', 'ZOOM', name='platform', create_type=False), nullable=False),
    sa.Column('platform_message_id', sa.String(length=255), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'READ', 'ARCHIVED', 'DELETED', 'FAILED_IMPORT', 'SYNCING', name='communicationstatus'), nullable=False),
    sa.Column('importance', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communications_platform_message_id'), 'communications', ['platform_message_id'], unique=False)
    op.create_table('sync_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cursor', sa.String(length=512), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_histories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('messages_imported', sa.Integer(), nullable=False),
    sa.Column('attachments_imported', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('error', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('communication_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('communication_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['communication_id'], ['communications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participants')
    op.drop_table('attachments')
    op.drop_table('sync_histories')
    op.drop_table('sync_checkpoints')
    op.drop_index(op.f('ix_communications_platform_message_id'), table_name='communications')
    op.drop_table('communications')
    op.drop_table('connectors')
    op.drop_index(op.f('ix_conversations_platform_conversation_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
